title: <p align="center"> Arijit Sengupta </p>
logo: /assets/img/logo.png
description: <p align="center">
 
  <a href="https://www.linkedin.com/in/arijitrijsengupta/">LinkedIn</a> |
  <a href="https://github.com/sengupta-arijit-rij">GitHub</a>
  
  <br>   
  I'm working on Machine learning related problems.
  
  <br>
  </p>
theme: jekyll-theme-minimal
