title: <p align="center"> Arijit Sengupta </p>
logo: /assets/img/0D21F6F9-88C8-403E-884D-F61E7A3A6F5F_1_201_a.jpeg
description: <p align="center">
  <a href="https://www.linkedin.com/in/arijitrijsengupta/">LinkedIn</a> |
  <a href="https://github.com/sengupta-arijit-rij">GitHub</a>
  <br>   
  I'm working on Machine learning related problems.
  <br>
  </p>
  
theme: jekyll-theme-minimal
